export const makroPages = [
	'https://www.online.makro.pl/shop/category/nabia%C5%82',
	// 'https://www.online.makro.pl/shop/category/kawa-herbata-kakao',
	// 'https://www.online.makro.pl/shop/category/soki-napoje-wody',
	// 'https://www.online.makro.pl/shop/category/s%C5%82odycze-i-przek%C4%85ski',
	// 'https://www.online.makro.pl/shop/category/konserwy-i-przetwory',
	// 'https://www.online.makro.pl/shop/category/oleje-oliwy-ocet',
	// 'https://www.online.makro.pl/shop/category/przyprawy',
	// 'https://www.online.makro.pl/shop/category/bakalie',
	// 'https://www.online.makro.pl/shop/category/cukier-i-s%C5%82odziki',
	// 'https://www.online.makro.pl/shop/category/piekarnia',
	// 'https://www.online.makro.pl/shop/category/do-pieczenia',
	// 'https://www.online.makro.pl/shop/category/p%C5%82atki-%C5%9Bniadaniowe',
	// 'https://www.online.makro.pl/shop/category/artyku%C5%82y-biurowe',
	// 'https://www.online.makro.pl/shop/category/artyku%C5%82y-jednorazowe',
	// 'https://www.online.makro.pl/shop/category/detergenty',
	// 'https://www.online.makro.pl/shop/category/kosmetyki-higiena-osobista',
	// 'https://www.online.makro.pl/shop/category/paczki',
	// 'https://www.online.makro.pl/shop/category/artyku%C5%82y-przemys%C5%82owe',
];
